# Generated by Django 2.0 on 2020-05-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porders',
            fields=[
                ('porder_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_gender', models.CharField(max_length=10)),
                ('P_userid', models.CharField(max_length=100)),
                ('P_sport', models.IntegerField()),
                ('P_number', models.IntegerField()),
                ('P_level', models.IntegerField()),
                ('P_pgender', models.IntegerField()),
                ('P_times', models.TimeField()),
                ('P_date', models.DateField()),
                ('P_createdatetime', models.DateTimeField(auto_now=True)),
                ('P_latitudes', models.FloatField()),
                ('P_longitudes', models.FloatField()),
                ('P_address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('porder_id',),
            },
        ),
    ]
