# Generated by Django 2.0 on 2020-05-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculateApi', '0002_pcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puorder',
            fields=[
                ('Puorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('porder_id', models.CharField(max_length=1000)),
                ('P_userid', models.CharField(max_length=100)),
                ('P_createdatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='porders',
            name='P_hasnum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
