# Generated by Django 2.0 on 2020-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculateApi', '0003_auto_20200525_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='porders',
            name='P_suc',
            field=models.BooleanField(default=False),
        ),
    ]
