# Generated by Django 2.0 on 2020-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculateApi', '0004_porders_p_suc'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(default=0)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
